### ISSUE TITLE
Changing the color of hostname and user

### ISSUE THREAD

**Issue by SerhiiZahuba** [mbrav/dotfiles#1]
I really liked your scripts. But I noticed a problem. As you can see on my screen, the user and host name are white letters on a white background. How can it be fixed?
![image](https://github.com/mbrav/dotfiles/assets/36307887/866599a0-5e09-4760-bf59-3c487a7d0cbf)

**Comment by mbrav** [comment]
Hi @SerhiiZahuba. In order for the terminal to display those symbols correctly, you must install one of many [Nerd Fonts](https://www.nerdfonts.com) and configure your terminal to use one of them.
